// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/option.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from proto/option.proto</summary>
  public static partial class OptionReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/option.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OptionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJwcm90by9vcHRpb24ucHJvdG8SBXByb3RvGiBnb29nbGUvcHJvdG9idWYv",
            "ZGVzY3JpcHRvci5wcm90byJQCgpTdHJpbmdPcHRzEhQKB21heF9sZW4YASAB",
            "KAVIAIgBARIUCgdtaW5fbGVuGAIgASgFSAGIAQFCCgoIX21heF9sZW5CCgoI",
            "X21pbl9sZW46RgoKc3RyaW5nT3B0cxIdLmdvb2dsZS5wcm90b2J1Zi5GaWVs",
            "ZE9wdGlvbnMY0IYDIAEoCzIRLnByb3RvLlN0cmluZ09wdHNCN1o1Z2l0aHVi",
            "LmNvbS9DQTIyLWdhbWUtY3JlYXRvcnMvY29va2luZ2JvbWItcHJvdG8vcHJv",
            "dG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { OptionExtensions.StringOpts }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.StringOpts), global::Proto.StringOpts.Parser, new[]{ "MaxLen", "MinLen" }, new[]{ "MaxLen", "MinLen" }, null, null, null)
          }));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of proto/option.proto</summary>
  public static partial class OptionExtensions {
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, global::Proto.StringOpts> StringOpts =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, global::Proto.StringOpts>(50000, pb::FieldCodec.ForMessage(400002, global::Proto.StringOpts.Parser));
  }

  #region Messages
  public sealed partial class StringOpts : pb::IMessage<StringOpts>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StringOpts> _parser = new pb::MessageParser<StringOpts>(() => new StringOpts());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StringOpts> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.OptionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StringOpts() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StringOpts(StringOpts other) : this() {
      _hasBits0 = other._hasBits0;
      maxLen_ = other.maxLen_;
      minLen_ = other.minLen_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StringOpts Clone() {
      return new StringOpts(this);
    }

    /// <summary>Field number for the "max_len" field.</summary>
    public const int MaxLenFieldNumber = 1;
    private int maxLen_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MaxLen {
      get { if ((_hasBits0 & 1) != 0) { return maxLen_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        maxLen_ = value;
      }
    }
    /// <summary>Gets whether the "max_len" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasMaxLen {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "max_len" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMaxLen() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "min_len" field.</summary>
    public const int MinLenFieldNumber = 2;
    private int minLen_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MinLen {
      get { if ((_hasBits0 & 2) != 0) { return minLen_; } else { return 0; } }
      set {
        _hasBits0 |= 2;
        minLen_ = value;
      }
    }
    /// <summary>Gets whether the "min_len" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasMinLen {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "min_len" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMinLen() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StringOpts);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StringOpts other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MaxLen != other.MaxLen) return false;
      if (MinLen != other.MinLen) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasMaxLen) hash ^= MaxLen.GetHashCode();
      if (HasMinLen) hash ^= MinLen.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasMaxLen) {
        output.WriteRawTag(8);
        output.WriteInt32(MaxLen);
      }
      if (HasMinLen) {
        output.WriteRawTag(16);
        output.WriteInt32(MinLen);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasMaxLen) {
        output.WriteRawTag(8);
        output.WriteInt32(MaxLen);
      }
      if (HasMinLen) {
        output.WriteRawTag(16);
        output.WriteInt32(MinLen);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasMaxLen) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxLen);
      }
      if (HasMinLen) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MinLen);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StringOpts other) {
      if (other == null) {
        return;
      }
      if (other.HasMaxLen) {
        MaxLen = other.MaxLen;
      }
      if (other.HasMinLen) {
        MinLen = other.MinLen;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MaxLen = input.ReadInt32();
            break;
          }
          case 16: {
            MinLen = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MaxLen = input.ReadInt32();
            break;
          }
          case 16: {
            MinLen = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
