// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from proto/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNwcm90by9zZXJ2aWNlLnByb3RvEgVwcm90bxoTcHJvdG8vbWVzc2FnZS5w",
            "cm90bzJICg9BY2NvdW50U2VydmljZXMSNQoGU2lnbnVwEhQucHJvdG8uU2ln",
            "bnVwUmVxdWVzdBoVLnByb3RvLlNpZ251cFJlc3BvbnNlQjdaNWdpdGh1Yi5j",
            "b20vQ0EyMi1nYW1lLWNyZWF0b3JzL2Nvb2tpbmdib21iLXByb3RvL3Byb3Rv",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.MessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
