// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/game/service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from proto/game/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/game/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chhwcm90by9nYW1lL3NlcnZpY2UucHJvdG8SBXByb3RvGhhwcm90by9nYW1l",
            "L21lc3NhZ2UucHJvdG8ynAIKD0FjY291bnRTZXJ2aWNlcxI5CgdDb25uZWN0",
            "EhUucHJvdG8uQ29ubmVjdFJlcXVlc3QaFy5wcm90by5Db25uZWN0aW9uU3Rh",
            "dHVzEjwKCkRpc2Nvbm5lY3QSFS5wcm90by5Db25uZWN0UmVxdWVzdBoXLnBy",
            "b3RvLkNvbm5lY3Rpb25TdGF0dXMSRQoTR2V0Q29ubmVjdGlvblN0YXR1cxIV",
            "LnByb3RvLkNvbm5lY3RSZXF1ZXN0GhcucHJvdG8uQ29ubmVjdGlvblN0YXR1",
            "cxJJChNDaGFyYWN0ZXJEYXRhU3RyZWFtEhQucHJvdG8uQ2hhcmFjdGVyRGF0",
            "YRoYLnByb3RvLkNoYXJhY3RlckRhdGFMaXN0KAEwAUI8WjpnaXRodWIuY29t",
            "L0NBMjItZ2FtZS1jcmVhdG9ycy9jb29raW5nYm9tYi1wcm90by9wcm90by9n",
            "YW1lYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.MessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
