// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/api/service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from proto/api/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/api/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chdwcm90by9hcGkvc2VydmljZS5wcm90bxIFcHJvdG8aF3Byb3RvL2FwaS9t",
            "ZXNzYWdlLnByb3RvMukBCg9BY2NvdW50U2VydmljZXMSNQoGU2lnbnVwEhQu",
            "cHJvdG8uU2lnbnVwUmVxdWVzdBoVLnByb3RvLlNpZ251cFJlc3BvbnNlElAK",
            "D0dldFNlc3Npb25Ub2tlbhIdLnByb3RvLkdldFNlc3Npb25Ub2tlblJlcXVl",
            "c3QaHi5wcm90by5HZXRTZXNzaW9uVG9rZW5SZXNwb25zZRJNCg5HZXRBY2Nv",
            "dW50SW5mbxIcLnByb3RvLkdldEFjY291bnRJbmZvUmVxdWVzdBodLnByb3Rv",
            "LkdldEFjY291bnRJbmZvUmVzcG9uc2VCO1o5Z2l0aHViLmNvbS9DQTIyLWdh",
            "bWUtY3JlYXRvcnMvY29va2luZ2JvbWItcHJvdG8vcHJvdG8vYXBpYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.MessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
