// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: proto/game/model.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionStatusEnum int32

const (
	ConnectionStatusEnum_CONNECTION_UNSPECIFIED ConnectionStatusEnum = 0 //初期値 正常でない値 接続できていないと考えて良い
	ConnectionStatusEnum_CONNECTING             ConnectionStatusEnum = 1 //接続を試行中
	ConnectionStatusEnum_CONNECTED              ConnectionStatusEnum = 2 //接続済み 各種APIにアクセスする準備が整っている
	ConnectionStatusEnum_DISCONNECTED_BY_CLIENT ConnectionStatusEnum = 3 //クライアント側からの要求によって、切断された
	ConnectionStatusEnum_DISCONNECTED_BY_SERVER ConnectionStatusEnum = 4 //ゲーム終了等の理由により、サーバー側から切断された
	ConnectionStatusEnum_DISCONNECTED           ConnectionStatusEnum = 5 //上記以外の理由により、切断された
	ConnectionStatusEnum_CONNECTION_FAIL        ConnectionStatusEnum = 6 //CONNECTINGから遷移する 接続要求は失敗した
)

// Enum value maps for ConnectionStatusEnum.
var (
	ConnectionStatusEnum_name = map[int32]string{
		0: "CONNECTION_UNSPECIFIED",
		1: "CONNECTING",
		2: "CONNECTED",
		3: "DISCONNECTED_BY_CLIENT",
		4: "DISCONNECTED_BY_SERVER",
		5: "DISCONNECTED",
		6: "CONNECTION_FAIL",
	}
	ConnectionStatusEnum_value = map[string]int32{
		"CONNECTION_UNSPECIFIED": 0,
		"CONNECTING":             1,
		"CONNECTED":              2,
		"DISCONNECTED_BY_CLIENT": 3,
		"DISCONNECTED_BY_SERVER": 4,
		"DISCONNECTED":           5,
		"CONNECTION_FAIL":        6,
	}
)

func (x ConnectionStatusEnum) Enum() *ConnectionStatusEnum {
	p := new(ConnectionStatusEnum)
	*p = x
	return p
}

func (x ConnectionStatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionStatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_model_proto_enumTypes[0].Descriptor()
}

func (ConnectionStatusEnum) Type() protoreflect.EnumType {
	return &file_proto_game_model_proto_enumTypes[0]
}

func (x ConnectionStatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionStatusEnum.Descriptor instead.
func (ConnectionStatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_model_proto_rawDescGZIP(), []int{0}
}

type Characters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Characters []*Character `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
}

func (x *Characters) Reset() {
	*x = Characters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Characters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Characters) ProtoMessage() {}

func (x *Characters) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Characters.ProtoReflect.Descriptor instead.
func (*Characters) Descriptor() ([]byte, []int) {
	return file_proto_game_model_proto_rawDescGZIP(), []int{0}
}

func (x *Characters) GetCharacters() []*Character {
	if x != nil {
		return x.Characters
	}
	return nil
}

type Character struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsActive   bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Position   *Position              `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Rotation   *Rotation              `protobuf:"bytes,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Velocity   *Velocity              `protobuf:"bytes,5,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Keyinput   *KeyInput              `protobuf:"bytes,6,opt,name=keyinput,proto3" json:"keyinput,omitempty"`
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}

func (x *Character) Reset() {
	*x = Character{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_proto_game_model_proto_rawDescGZIP(), []int{1}
}

func (x *Character) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Character) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Character) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Character) GetRotation() *Rotation {
	if x != nil {
		return x.Rotation
	}
	return nil
}

func (x *Character) GetVelocity() *Velocity {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *Character) GetKeyinput() *KeyInput {
	if x != nil {
		return x.Keyinput
	}
	return nil
}

func (x *Character) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type MatchInfomationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MatchInfomationRequest) Reset() {
	*x = MatchInfomationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchInfomationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchInfomationRequest) ProtoMessage() {}

func (x *MatchInfomationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchInfomationRequest.ProtoReflect.Descriptor instead.
func (*MatchInfomationRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_model_proto_rawDescGZIP(), []int{2}
}

type MatchInfomationResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accounts []*MatchAccountInfo `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
}

func (x *MatchInfomationResponce) Reset() {
	*x = MatchInfomationResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchInfomationResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchInfomationResponce) ProtoMessage() {}

func (x *MatchInfomationResponce) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchInfomationResponce.ProtoReflect.Descriptor instead.
func (*MatchInfomationResponce) Descriptor() ([]byte, []int) {
	return file_proto_game_model_proto_rawDescGZIP(), []int{3}
}

func (x *MatchInfomationResponce) GetAccounts() []*MatchAccountInfo {
	if x != nil {
		return x.Accounts
	}
	return nil
}

var File_proto_game_model_proto protoreflect.FileDescriptor

var file_proto_game_model_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x0a,
	0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x12, 0x30, 0x0a, 0x0a, 0x63, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x52, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x22, 0xa9, 0x02, 0x0a,
	0x09, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73,
	0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69,
	0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x2b, 0x0a, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x6c, 0x6f,
	0x63, 0x69, 0x74, 0x79, 0x52, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x12, 0x2b,
	0x0a, 0x08, 0x6b, 0x65, 0x79, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x65, 0x79, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x3b, 0x0a, 0x0b, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x49, 0x6e, 0x66, 0x6f, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x4e, 0x0a, 0x17, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x33, 0x0a,
	0x08, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x73, 0x2a, 0xb0, 0x01, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x16, 0x43,
	0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4f, 0x4e, 0x4e, 0x45,
	0x43, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4e, 0x4e, 0x45,
	0x43, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e,
	0x4e, 0x45, 0x43, 0x54, 0x45, 0x44, 0x5f, 0x42, 0x59, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54,
	0x10, 0x03, 0x12, 0x1a, 0x0a, 0x16, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54,
	0x45, 0x44, 0x5f, 0x42, 0x59, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x10, 0x04, 0x12, 0x10,
	0x0a, 0x0c, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x05,
	0x12, 0x13, 0x0a, 0x0f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x46,
	0x41, 0x49, 0x4c, 0x10, 0x06, 0x42, 0x49, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x41, 0x32, 0x32, 0x2d, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x62, 0x6f,
	0x6d, 0x62, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67,
	0x61, 0x6d, 0x65, 0xaa, 0x02, 0x0a, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x61, 0x6d, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_game_model_proto_rawDescOnce sync.Once
	file_proto_game_model_proto_rawDescData = file_proto_game_model_proto_rawDesc
)

func file_proto_game_model_proto_rawDescGZIP() []byte {
	file_proto_game_model_proto_rawDescOnce.Do(func() {
		file_proto_game_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_game_model_proto_rawDescData)
	})
	return file_proto_game_model_proto_rawDescData
}

var file_proto_game_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_game_model_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_game_model_proto_goTypes = []interface{}{
	(ConnectionStatusEnum)(0),       // 0: proto.ConnectionStatusEnum
	(*Characters)(nil),              // 1: proto.Characters
	(*Character)(nil),               // 2: proto.Character
	(*MatchInfomationRequest)(nil),  // 3: proto.MatchInfomationRequest
	(*MatchInfomationResponce)(nil), // 4: proto.MatchInfomationResponce
	(*Position)(nil),                // 5: proto.Position
	(*Rotation)(nil),                // 6: proto.Rotation
	(*Velocity)(nil),                // 7: proto.Velocity
	(*KeyInput)(nil),                // 8: proto.KeyInput
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
	(*MatchAccountInfo)(nil),        // 10: proto.MatchAccountInfo
}
var file_proto_game_model_proto_depIdxs = []int32{
	2,  // 0: proto.Characters.characters:type_name -> proto.Character
	5,  // 1: proto.Character.position:type_name -> proto.Position
	6,  // 2: proto.Character.rotation:type_name -> proto.Rotation
	7,  // 3: proto.Character.velocity:type_name -> proto.Velocity
	8,  // 4: proto.Character.keyinput:type_name -> proto.KeyInput
	9,  // 5: proto.Character.update_time:type_name -> google.protobuf.Timestamp
	10, // 6: proto.MatchInfomationResponce.accounts:type_name -> proto.MatchAccountInfo
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_game_model_proto_init() }
func file_proto_game_model_proto_init() {
	if File_proto_game_model_proto != nil {
		return
	}
	file_proto_game_structure_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_game_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Characters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Character); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchInfomationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchInfomationResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_game_model_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_model_proto_goTypes,
		DependencyIndexes: file_proto_game_model_proto_depIdxs,
		EnumInfos:         file_proto_game_model_proto_enumTypes,
		MessageInfos:      file_proto_game_model_proto_msgTypes,
	}.Build()
	File_proto_game_model_proto = out.File
	file_proto_game_model_proto_rawDesc = nil
	file_proto_game_model_proto_goTypes = nil
	file_proto_game_model_proto_depIdxs = nil
}
