// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/game/service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto.Game {

  /// <summary>Holder for reflection information generated from proto/game/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/game/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chhwcm90by9nYW1lL3NlcnZpY2UucHJvdG8SBXByb3RvGhhwcm90by9nYW1l",
            "L21lc3NhZ2UucHJvdG8yVQoMR2FtZVNlcnZpY2VzEkUKDkdhbWVEYXRhU3Ry",
            "ZWFtEhYucHJvdG8uR2FtZURhdGFSZXF1ZXN0GhcucHJvdG8uR2FtZURhdGFS",
            "ZXNwb25zZSgBMAFCSVo6Z2l0aHViLmNvbS9DQTIyLWdhbWUtY3JlYXRvcnMv",
            "Y29va2luZ2JvbWItcHJvdG8vcHJvdG8vZ2FtZaoCClByb3RvLkdhbWViBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.Game.MessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
