// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/game/service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from proto/game/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/game/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chhwcm90by9nYW1lL3NlcnZpY2UucHJvdG8SBXByb3RvGhhwcm90by9nYW1l",
            "L21lc3NhZ2UucHJvdG8ypAIKDEdhbWVTZXJ2aWNlcxI+CgdDb25uZWN0Ehgu",
            "cHJvdG8uQ29ubmVjdGlvblJlcXVlc3QaGS5wcm90by5Db25uZWN0aW9uUmVz",
            "cG9uc2USQQoKRGlzY29ubmVjdBIYLnByb3RvLkNvbm5lY3Rpb25SZXF1ZXN0",
            "GhkucHJvdG8uQ29ubmVjdGlvblJlc3BvbnNlEkoKE0dldENvbm5lY3Rpb25T",
            "dGF0dXMSGC5wcm90by5Db25uZWN0aW9uUmVxdWVzdBoZLnByb3RvLkNvbm5l",
            "Y3Rpb25SZXNwb25zZRJFCg5HYW1lRGF0YVN0cmVhbRIWLnByb3RvLkdhbWVE",
            "YXRhUmVxdWVzdBoXLnByb3RvLkdhbWVEYXRhUmVzcG9uc2UoATABQjxaOmdp",
            "dGh1Yi5jb20vQ0EyMi1nYW1lLWNyZWF0b3JzL2Nvb2tpbmdib21iLXByb3Rv",
            "L3Byb3RvL2dhbWViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.MessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
