name: test

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "**.md"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Checkout
      uses: actions/checkout@v2

    - name: Run test
      run: make test
